# Generated by Django 5.0.2 on 2024-03-06 06:43

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('passport', models.PositiveBigIntegerField()),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsureOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bank_number', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('медицинское учреждение', 'медицинское учреждение'), ('автотранспортное предприятие', 'автотранспортное предприятие'), ('учебное заведение', 'учебное заведение'), ('другое', 'другое')], max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summ', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1023)),
                ('damage_summ', models.PositiveIntegerField()),
                ('payment', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.employee')),
                ('individual', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.individual')),
            ],
        ),
        migrations.CreateModel(
            name='InsureAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('passport', models.PositiveBigIntegerField()),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('insureorganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insureorganization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.organization'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.individual')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insureagent')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.type'),
        ),
    ]
