# Generated by Django 5.0.2 on 2024-03-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecase',
            name='individual',
        ),
    ]
