# Generated by Django 5.0.2 on 2024-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_remove_insurancecase_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='patronymic',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
