# Generated by Django 5.0.2 on 2024-03-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.organization'),
        ),
    ]
