# Generated by Django 5.0.2 on 2024-03-12 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_alter_contract_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecase',
            name='contract',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract'),
            preserve_default=False,
        ),
    ]
