# Generated by Django 5.0.2 on 2024-03-05 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('location_description', models.TextField(null=True)),
                ('participating_terms', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lab2_manage.conference')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lab2_manage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, null=True)),
                ('result', models.BooleanField(null=True)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lab2_manage.conference')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lab2_manage.user')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='user_registered',
            field=models.ManyToManyField(blank=True, null=True, to='Lab2_manage.user'),
        ),
    ]
