# Generated by Django 5.0.2 on 2024-03-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab2_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
